### ISSUE TITLE
No module named 'polars.utils'

### ISSUE THREAD

**Issue by schemaitat** [functime-org/functime#253]
**Describe the bug**

When importing functime v0.9.5. with polars v.1.6.0 the "ModuleNotFoundError: No module named 'polars.utils' Error is thrown.

**To Reproduce**

1. Run `uv run --with 'polars==1.6' --with 'functime==0.9.5' issue.py`,
where issue.py contains the following content: 'import functime' and `uv 0.3.1`.

**Expected behavior**
No errors are thrown, when executing the above command.

**Desktop:**
 - OS: Ubuntu 22.04.4 LTS

**Comment by EtienneT** [comment]
polars > 1.16 have some major improvements for rolling, this would be really nice to have functime support it.

**Comment by lucharo** [comment]
I am facing the issue when trying to run [`quickstart.py`](https://docs.functime.ai/user-guide/forecasting/) within a marimo notebook using python 3.12: 

```sh
UV_PYTHON=3.12 uvx --with functime marimo edit tryfunctime.py
```

error:

```python
Traceback (most recent call last):
  File "/Users/lucharo/.cache/uv/archive-v0/GVYseca7chh6iYWxUmrrx/lib/python3.12/site-packages/marimo/_runtime/executor.py", line 141, in execute_cell
    exec(cell.body, glbls)
  Cell marimo:///Users/lucharo/fe.py#cell=cell-0, line 6, in <module>
    from functime.cross_validation import train_test_split
  File "/Users/lucharo/.cache/uv/archive-v0/GVYseca7chh6iYWxUmrrx/lib/python3.12/site-packages/functime/__init__.py", line 7, in <module>
    from functime.feature_extractors import FeatureExtractor  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lucharo/.cache/uv/archive-v0/GVYseca7chh6iYWxUmrrx/lib/python3.12/site-packages/functime/feature_extractors.py", line 8, in <module>
    from polars.utils.udfs import _get_shared_lib_location
ModuleNotFoundError: No module named 'polars.utils'
```

**Comment by MathieuCayssol** [comment]
We have made the upgrade to the latest library version. We would really appreciate if you could test the pre release here: https://pypi.org/project/functime/1.0.0rc1/
